### ISSUE TITLE
Type Error: Expected int32, got list containing Tensors of type '_Message' instead

### ISSUE THREAD

**Issue by irisyjohnson** [amitadate/S-LSTM-GAN-MNIST#1]
line 243

**Comment by irisyjohnson** [comment]
solved: https://stackoverflow.com/questions/41813665/tensorflow-slim-typeerror-expected-int32-got-list-containing-tensors-of-type

**Comment by jchook** [comment]
Will you explain how you used this to solve your problem? Did you have to roll back to an older TF version?
