### ISSUE TITLE
ValueError: Dimensions must be equal, 

### ISSUE THREAD

**Issue by irisyjohnson** [amitadate/S-LSTM-GAN-MNIST#2]
ValueError: Dimensions must be equal, but are 800 and 596 for 'model_full/RNN_d/rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/basic_lstm_cell/MatMul_1' (op: 'MatMul') with input shapes: [128,800], [596,1600].

**Comment by sweetatyagiaz** [comment]
I am also getting the same error 
 Dimensions must be equal, but are 800 and 596 for 'model_full/RNN_d/rnn/while/rnn/multi_rnn_cell/cell_0/basic_lstm_cell/MatMul_1' (op: 'MatMul') with input shapes: [128,800], [596,1600].

**Comment by wenfengand** [comment]
You need to roll back your tensorflow version to 0.12.1 to get the code running.

And replace all `configobj().batch_size/2`  with `int(configobj().batch_size/2)`

![image](https://user-images.githubusercontent.com/29633871/56480770-28bd4f00-64ee-11e9-87c4-0a24b1802af0.png)

I'm still working on porting it to the modern tensorflow version.
